println("yo", "lo")
println("Hello, world!")
println("string ", 42)
println(true, false)
print(4, 2)
println(42)
print(true)
print(42)
print(false)
println()
println("Hello, world!")
println("Hello", ",", " ", "world", "!")
println(42, "newline\nafter newline\t", nothing)
println("\\\\")
println("\\\"")
